development:
  adapter: postgresql
  database: ember-crm_development
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: ember-crm_test
  host: localhost
  pool: 5
  timeout: 5000

staging:
  adapter: postgresql
  database: ember-crm_staging
  host: localhost
  user: <%= ENV["STAGING_DB_USER"] %>
  password: <%= ENV["STAGING_DB_PASSWORD"] %>
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: ember-crm_production
  host: localhost
  user: <%= ENV["PRODUCTION_DB_USER"] %>
  password: <%= ENV["PRODUCTION_DB_PASSWORD"] %>
  pool: 5
  timeout: 5000

